import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import { downloadCsvSections } from '@/utils/exportFile';
import type { ActivityItem, AppointmentRow, MetricConfig } from '@/types';

export type ExportFormat = 'pdf' | 'csv';

export interface ExportSections {
  kpis: boolean;
  queue: boolean;
  activity: boolean;
}

export interface DashboardReportData {
  clinicName: string;
  generatedBy: string;
  metrics: MetricConfig[];
  appointments: AppointmentRow[];
  activity: ActivityItem[];
  sections: ExportSections;
}

const TEAL: [number, number, number] = [0, 125, 114];
const INK: [number, number, number] = [24, 35, 56];
const MUTED: [number, number, number] = [107, 117, 135];

/** The built-in PDF fonts only cover Latin-1, so drop arrows/symbols that would print as garbage. */
const pdfSafe = (text: string) => text.replace(/[^\x20-\x7E\u00A0-\u00FF\u2022\u2013\u2014]/g, '').replace(/\s+/g, ' ').trim();

const titleCase = (label: string) => label.toLowerCase().replace(/(^|\s)(\w)/g, (_, a, b) => a + b.toUpperCase());

function pad(n: number) { return String(n).padStart(2, '0'); }

export function buildFilename(format: ExportFormat, now = new Date()): string {
  const date = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
  const time = `${pad(now.getHours())}${pad(now.getMinutes())}`;
  return `CuraClinic_Daily_Summary_${date}_${time}.${format}`;
}

function describe(now: Date) {
  return {
    reportDate: now.toLocaleDateString('en-US', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }),
    generatedAt: now.toLocaleString('en-US', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }),
  };
}

export function exportDashboardCsv(data: DashboardReportData, filename: string, now = new Date()): void {
  const { reportDate, generatedAt } = describe(now);
  const preamble = [
    [`${data.clinicName} - Daily Operations Summary`],
    ['Report date', reportDate],
    ['Generated', generatedAt],
    ['Generated by', data.generatedBy],
    ['Confidential - contains protected patient information'],
  ];
  const sections = [];
  if (data.sections.kpis) {
    sections.push({
      title: 'Key metrics',
      headers: ['Metric', 'Value', 'Note'],
      rows: data.metrics.map((m) => [titleCase(m.label), m.value, m.note.replace(/^[^\p{L}\p{N}+]+/u, '')]),
    });
  }
  if (data.sections.queue) {
    sections.push({
      title: "Today's appointments queue",
      headers: ['Time', 'Patient', 'Age / Sex', 'Doctor', 'Reason for visit'],
      rows: data.appointments,
    });
  }
  if (data.sections.activity) {
    sections.push({
      title: 'Recent activity',
      headers: ['Event', 'When / Source'],
      rows: data.activity.map((a) => [a.text, a.meta]),
    });
  }
  downloadCsvSections(filename, preamble, sections);
}

export function exportDashboardPdf(data: DashboardReportData, filename: string, now = new Date()): void {
  const { reportDate, generatedAt } = describe(now);
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentW = pageW - margin * 2;

  // Letterhead
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, pageW, 26, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(pdfSafe(data.clinicName), margin, 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Central Clinic & Specialty Suites', margin, 19);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Daily Operations Summary', pageW - margin, 13, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(reportDate, pageW - margin, 19, { align: 'right' });

  // Meta line
  doc.setTextColor(...MUTED);
  doc.setFontSize(8.5);
  doc.text(`Generated ${generatedAt}  |  Prepared by ${pdfSafe(data.generatedBy)}`, margin, 33);

  let y = 40;
  const heading = (text: string) => {
    if (y > pageH - 40) { doc.addPage(); y = 18; }
    doc.setTextColor(...INK);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(text, margin, y);
    doc.setDrawColor(...TEAL);
    doc.setLineWidth(0.6);
    doc.line(margin, y + 2, margin + 12, y + 2);
    y += 8;
  };
  const afterTable = () => { y = ((doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y) + 10; };

  if (data.sections.kpis) {
    heading('Key metrics');
    const perRow = 3;
    const gap = 4;
    const boxW = (contentW - gap * (perRow - 1)) / perRow;
    const boxH = 22;
    data.metrics.forEach((m, i) => {
      const col = i % perRow;
      const row = Math.floor(i / perRow);
      const x = margin + col * (boxW + gap);
      const top = y + row * (boxH + gap);
      doc.setFillColor(246, 248, 251);
      doc.setDrawColor(230, 233, 240);
      doc.setLineWidth(0.3);
      doc.roundedRect(x, top, boxW, boxH, 2, 2, 'FD');
      doc.setFillColor(...TEAL);
      doc.rect(x, top + 3, 1, boxH - 6, 'F');
      doc.setTextColor(...MUTED);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.text(pdfSafe(titleCase(m.label)), x + 5, top + 6.5);
      doc.setTextColor(...INK);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(15);
      doc.text(pdfSafe(m.value), x + 5, top + 14);
      doc.setTextColor(...MUTED);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.text(pdfSafe(m.note), x + 5, top + 19);
    });
    const rows = Math.ceil(data.metrics.length / perRow);
    y += rows * (boxH + gap) + 4;
  }

  const tableStyle = {
    theme: 'striped' as const,
    margin: { left: margin, right: margin },
    styles: { font: 'helvetica', fontSize: 9, cellPadding: 2.6, textColor: INK, lineColor: [230, 233, 240] as [number, number, number] },
    headStyles: { fillColor: TEAL, textColor: 255, fontStyle: 'bold' as const },
    alternateRowStyles: { fillColor: [247, 249, 251] as [number, number, number] },
  };

  if (data.sections.queue) {
    heading("Today's appointments queue");
    autoTable(doc, {
      ...tableStyle,
      startY: y,
      head: [['Time', 'Patient', 'Age / Sex', 'Doctor', 'Reason for visit']],
      body: data.appointments.length
        ? data.appointments.map((r) => r.map((c) => pdfSafe(String(c))))
        : [[{ content: 'No appointments scheduled.', colSpan: 5, styles: { halign: 'center' as const, textColor: MUTED } }]],
    });
    afterTable();
  }

  if (data.sections.activity) {
    heading('Recent activity');
    autoTable(doc, {
      ...tableStyle,
      startY: y,
      head: [['Event', 'When / Source']],
      body: data.activity.map((a) => [pdfSafe(a.text), pdfSafe(a.meta)]),
      columnStyles: { 1: { cellWidth: 62, textColor: MUTED } },
    });
    afterTable();
  }

  // Footer on every page
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p += 1) {
    doc.setPage(p);
    doc.setDrawColor(230, 233, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, pageH - 14, pageW - margin, pageH - 14);
    doc.setTextColor(...MUTED);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.text('CONFIDENTIAL - Contains protected patient information. Handle in line with clinic privacy policy.', margin, pageH - 9);
    doc.text(`Page ${p} of ${pages}`, pageW - margin, pageH - 9, { align: 'right' });
  }

  doc.save(filename);
}