import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import { csvSectionsBlob } from '@/utils/exportFile';
import { formatDay } from '@/utils/reportRange';
import type { DateRange } from '@/utils/reportRange';
import type { ReportDataset, ReportSection } from '@/services/reportService';

export type ReportFormat = 'pdf' | 'csv';

export interface ReportMeta {
  clinicName: string;
  clinicAddress: string;
  generatedBy: string;
  generatedAt: Date;
  range: DateRange;
}

export interface GeneratedFile {
  blob: Blob;
  filename: string;
}

type RGB = [number, number, number];
const TEAL: RGB = [0, 125, 114];
const INK: RGB = [24, 35, 56];
const MUTED: RGB = [107, 117, 135];
const LINE: RGB = [230, 233, 240];

/** The built-in PDF fonts only cover Latin-1, so drop symbols that would print as garbage. */
const pdfSafe = (text: string) => text.replace(/[^\x20-\x7E\u00A0-\u00FF\u2022\u2013\u2014]/g, ' ').replace(/\s+/g, ' ').trim();

const pad = (n: number) => String(n).padStart(2, '0');

export function buildFilename(dataset: ReportDataset, range: DateRange, format: ReportFormat): string {
  const span = range.start === range.end ? range.start : `${range.start}_to_${range.end}`;
  return `CuraClinic_${dataset.slug}_${span}.${format}`;
}

function formatGenerated(date: Date) {
  return `${formatDay(`${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`)} ${date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}`;
}

// ---------- CSV ----------

export function renderCsv(dataset: ReportDataset, meta: ReportMeta): GeneratedFile {
  const preamble: string[][] = [
    [`${meta.clinicName} - ${dataset.title}`],
    ['Period', meta.range.label],
    ['Generated', formatGenerated(meta.generatedAt)],
    ['Generated by', meta.generatedBy],
    ['Records', String(dataset.recordCount)],
    ...dataset.summary.map(([label, value]) => [label, value]),
    ...dataset.notes.map((note) => ['Note', note]),
    ['Confidential - contains protected patient information'],
  ];
  const sections = dataset.sections.map((s) => ({ title: s.title, headers: s.headers, rows: s.rows }));
  return { blob: csvSectionsBlob(preamble, sections), filename: buildFilename(dataset, meta.range, 'csv') };
}

// ---------- PDF ----------

function pdfRows(section: ReportSection, keep: number[]): string[][] {
  const money = new Set((section.money ?? []).map((h) => section.headers.indexOf(h)));
  return section.rows.map((row) => keep.map((i) => {
    const cell = row[i];
    if (typeof cell === 'number') {
      return money.has(i) ? cell.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : String(cell);
    }
    return pdfSafe(String(cell ?? ''));
  }));
}

export function renderPdf(dataset: ReportDataset, meta: ReportMeta): GeneratedFile {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: dataset.orientation });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;

  // Letterhead
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, pageW, 26, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.text(pdfSafe(meta.clinicName), margin, 12);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  if (meta.clinicAddress) doc.text(pdfSafe(meta.clinicAddress), margin, 19);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text(pdfSafe(dataset.title), pageW - margin, 12, { align: 'right' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(`Period: ${meta.range.label}`, pageW - margin, 19, { align: 'right' });

  doc.setTextColor(...MUTED);
  doc.setFontSize(8.5);
  doc.text(`Generated ${formatGenerated(meta.generatedAt)}  |  Prepared by ${pdfSafe(meta.generatedBy)}  |  Records: ${dataset.recordCount}`, margin, 33);

  const tableStyle = {
    theme: 'striped' as const,
    margin: { left: margin, right: margin },
    styles: { font: 'helvetica', fontSize: 8.5, cellPadding: 2.2, textColor: INK, lineColor: LINE, overflow: 'linebreak' as const },
    headStyles: { fillColor: TEAL, textColor: 255, fontStyle: 'bold' as const },
    alternateRowStyles: { fillColor: [247, 249, 251] as RGB },
  };
  let y = 40;
  const lastY = () => (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y;
  const heading = (text: string) => {
    if (y > pageH - 40) { doc.addPage(); y = 18; }
    doc.setTextColor(...INK);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11.5);
    doc.text(pdfSafe(text), margin, y);
    doc.setDrawColor(...TEAL);
    doc.setLineWidth(0.6);
    doc.line(margin, y + 2, margin + 12, y + 2);
    y += 6;
  };

  if (dataset.summary.length) {
    heading('Summary');
    autoTable(doc, {
      ...tableStyle,
      startY: y,
      body: dataset.summary.map(([label, value]) => [pdfSafe(label), pdfSafe(value)]),
      columnStyles: { 0: { cellWidth: 70, fontStyle: 'bold' } },
      tableWidth: 130,
    });
    y = lastY() + 9;
  }

  dataset.sections.forEach((section) => {
    const hide = new Set(section.pdfHide ?? []);
    const keep = section.headers.map((h, i) => (hide.has(h) ? -1 : i)).filter((i) => i >= 0);
    heading(section.title);
    autoTable(doc, {
      ...tableStyle,
      startY: y,
      head: [keep.map((i) => section.headers[i])],
      body: pdfRows(section, keep),
    });
    y = lastY() + 9;
  });

  if (dataset.notes.length) {
    if (y > pageH - 36) { doc.addPage(); y = 18; }
    doc.setTextColor(...MUTED);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    const lines = doc.splitTextToSize(dataset.notes.map((n) => `Note: ${pdfSafe(n)}`).join('\n'), pageW - margin * 2) as string[];
    doc.text(lines, margin, y);
  }

  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p += 1) {
    doc.setPage(p);
    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.3);
    doc.line(margin, pageH - 14, pageW - margin, pageH - 14);
    doc.setTextColor(...MUTED);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.text('CONFIDENTIAL - Contains protected patient information. Handle in line with clinic privacy policy.', margin, pageH - 9);
    doc.text(`Page ${p} of ${pages}`, pageW - margin, pageH - 9, { align: 'right' });
  }

  return { blob: doc.output('blob'), filename: buildFilename(dataset, meta.range, 'pdf') };
}

export function renderReport(format: ReportFormat, dataset: ReportDataset, meta: ReportMeta): GeneratedFile {
  return format === 'pdf' ? renderPdf(dataset, meta) : renderCsv(dataset, meta);
}